services:
  - type: web
    name: python-flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
