services:
  - type: web
    name: python-on-render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
