name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip code for deployment
        run: zip -r release.zip . -x "venv/*" ".git/*" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: badmintonenjoyer-python
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

      - name: Health check - verify app is up
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://badmintonenjoyer-python-a7b8frccccbygcbp.polandcentral-01.azurewebsites.net/)
          echo "HTTP Status: $STATUS_CODE"
          if [[ $STATUS_CODE -lt 200 || $STATUS_CODE -ge 400 ]]; then
            echo "Health check failed"
            exit 1
          else
            echo "Health check succeeded"
          fi
